### ISSUE TITLE
More rebuild log event need to be added incase of failure

### ISSUE THREAD

**Issue by kumarsudhish** [k8-proxy/glasswall-desktop#149]
More rebuild log event need to be added incase of failure

**Comment by nishantswarup** [comment]
Verified this issue on Prod build v0.1.6 and observed that all the raw logs has been added separately in the Raw Logs tab.
Hence marking this issue as Closed.
![image](https://user-images.githubusercontent.com/73164123/99260059-ecc0ac00-2840-11eb-9ac1-41030fdd9630.png)

**Comment by kumarsudhish** [comment]
Verified this issue on Prod build v0.1.6 and observed that all the raw logs has been added separately in the Raw Logs tab.
Hence marking this issue as Closed.
![image](https://user-images.githubusercontent.com/73164123/99260059-ecc0ac00-2840-11eb-9ac1-41030fdd9630.png)
