### ISSUE TITLE
Push all codebase to new Repo https://github.com/k8-proxy/glasswall-desktop

### ISSUE THREAD

**Issue by kumarsudhish** [k8-proxy/glasswall-desktop#16]
@kumarsudhish commented on [Fri Oct 16 2020](https://github.com/k8-proxy/k8-proxy-desktop/issues/159)

Push all codebase to new Repo https://github.com/k8-proxy/glasswall-desktop

**Comment by rajmbcoderx** [comment]
Pushed the Rebuild version of Glasswall desktop

**Comment by kumarsudhish** [comment]
Verified this issue on latest code push and observed that issue has been fixed and on every latest code commit and push it being merged in the Repo https://github.com/k8-proxy/glasswall-desktop and the fix is available on the portal https://glasswall-desktop.com/

Hence marking this issue as Done and Closed
