### ISSUE TITLE
To add a re-add the button to re-download the image incase user has stale image

### ISSUE THREAD

**Issue by kumarsudhish** [k8-proxy/glasswall-desktop#167]
To add a re-add the button to re-download the image incase user ahs stale image

**Comment by nishantswarup** [comment]
Verified this issue on latest Prod build v0.1.6 and observed that download button has been added. Hence marking this issue as Closed.
![image](https://user-images.githubusercontent.com/73164123/99258990-6192e680-283f-11eb-86cf-83931065a971.png)

**Comment by kumarsudhish** [comment]
Verified this issue on latest Prod build v0.1.6 and observed that download button has been added. Hence marking this issue as Closed.
![image](https://user-images.githubusercontent.com/73164123/99258990-6192e680-283f-11eb-86cf-83931065a971.png)
