### ISSUE TITLE
Change Rebuild Health Check label name in the side bar

### ISSUE THREAD

**Issue by kumarsudhish** [k8-proxy/glasswall-desktop#172]
Change Rebuild Health Check label name in the side bar

**Comment by nishantswarup** [comment]
Verified on Prod build and observed that Prod Health Check name has been changed. v0.1.6
![image](https://user-images.githubusercontent.com/73164123/99260780-dbc46a80-2841-11eb-99d3-e6d11c5173bf.png)

**Comment by kumarsudhish** [comment]
Verified on Prod build and observed that Prod Health Check name has been changed. v0.1.6
![image](https://user-images.githubusercontent.com/73164123/99260780-dbc46a80-2841-11eb-99d3-e6d11c5173bf.png)
