### ISSUE TITLE
Provide Server configuration for the Cloud

### ISSUE THREAD

**Issue by kumarsudhish** [k8-proxy/glasswall-desktop#173]
Provide Server configuration for the Cloud

**Comment by nishantswarup** [comment]
Verified this issue on latest Prod build v0.1.6 and observed it working fine. Hence marking this issue as Closed.
![image](https://user-images.githubusercontent.com/73164123/99260698-be8f9c00-2841-11eb-8075-6289ea478bfd.png)

**Comment by kumarsudhish** [comment]
Verified this issue on latest Prod build v0.1.6 and observed it working fine. Hence marking this issue as Closed.
![image](https://user-images.githubusercontent.com/73164123/99260698-be8f9c00-2841-11eb-8075-6289ea478bfd.png)
