### ISSUE TITLE
Not able to run the rebuild locally from latest codebase repo

### ISSUE THREAD

**Issue by kumarsudhish** [k8-proxy/glasswall-desktop#191]
Not able to run the rebuild locally from latest codebase repo, user is thrown back to the configuration page.
![image.png](https://images.zenhubusercontent.com/5f6b4534c344a37b7c855e35/1c2423cb-f63a-4e71-8574-5b96c4b6f15f)

**Comment by nishantswarup** [comment]
Verified this issue on latest Prod build v0.1.6 and observed that issue has been fixed.
Hence marking this issue as Closed.
![image](https://user-images.githubusercontent.com/73164123/99259909-b6832c80-2840-11eb-8104-8cabf536bdc5.png)

**Comment by kumarsudhish** [comment]
Verified this issue on latest Prod build v0.1.6 and observed that issue has been fixed.
Hence marking this issue as Closed.
![image](https://user-images.githubusercontent.com/73164123/99259909-b6832c80-2840-11eb-8104-8cabf536bdc5.png)
