### ISSUE TITLE
Color of all the tabs present in the left panel needs to be same

### ISSUE THREAD

**Issue by kumarsudhish** [k8-proxy/glasswall-desktop#195]
Color of all the tabs present in the left panel needs to be same

![image.png](https://images.zenhubusercontent.com/5f6b4534c344a37b7c855e35/a530a332-b870-481e-bc2b-b78881630ef1)

**Comment by nishantswarup** [comment]
Verified this issue on latest Prod build v0.1.6 and observed that icon has been fixed.
![image](https://user-images.githubusercontent.com/73164123/99259520-22b16080-2840-11eb-860c-0336e6031a57.png)

**Comment by kumarsudhish** [comment]
Verified this issue on latest Prod build v0.1.6 and observed that icon has been fixed.
![image](https://user-images.githubusercontent.com/73164123/99259520-22b16080-2840-11eb-860c-0336e6031a57.png)
