### ISSUE TITLE
Logs button from the Rebuild Local tab needs to be removed

### ISSUE THREAD

**Issue by kumarsudhish** [k8-proxy/glasswall-desktop#196]
Logs button from the Rebuild Local tab needs to be removed

![image.png](https://images.zenhubusercontent.com/5f6b4534c344a37b7c855e35/e22fc338-a1cd-4907-9460-0d661a58c91e)

**Comment by nishantswarup** [comment]
Verified this issue on latest Prod build v0.1.6 and observed that Logs button has been removed. Hence marking this issue as Closed.
![image](https://user-images.githubusercontent.com/73164123/99258662-ea5d5280-283e-11eb-828e-60ff9b3d4449.png)

**Comment by kumarsudhish** [comment]
Verified this issue on latest Prod build v0.1.6 and observed that Logs button has been removed. Hence marking this issue as Closed.
![image](https://user-images.githubusercontent.com/73164123/99258662-ea5d5280-283e-11eb-828e-60ff9b3d4449.png)
