### ISSUE TITLE
Application crashes on running the rebuild in sequential mode.

### ISSUE THREAD

**Issue by kumarsudhish** [k8-proxy/glasswall-desktop#218]
Application crashes on running the rebuild in sequential mode.

**Comment by nishantswarup** [comment]
Verified this issue on latest Prod build v0.1.6 and observed it working fine. Hence marking this issue as Closed.

**Comment by kumarsudhish** [comment]
Verified this issue on latest Prod build v0.1.6 and observed it working fine. Hence marking this issue as Closed.
