### ISSUE TITLE
Application hangs incase of large logs file size

### ISSUE THREAD

**Issue by kumarsudhish** [k8-proxy/glasswall-desktop#220]
Application hangs incase of large logs file size

**Comment by nishantswarup** [comment]
Verified this issue on latest Prod build v0.1.6 and observed it working fine. Hence marking this issue as Closed.
![image](https://user-images.githubusercontent.com/73164123/99260194-14177900-2841-11eb-9a2a-eba17d6beb59.png)

**Comment by kumarsudhish** [comment]
Verified this issue on latest Prod build v0.1.6 and observed it working fine. Hence marking this issue as Closed.
![image](https://user-images.githubusercontent.com/73164123/99260194-14177900-2841-11eb-9a2a-eba17d6beb59.png)
