### ISSUE TITLE
Llinux build is not published through GIT Action workflow

### ISSUE THREAD

**Issue by ajitpeter** [k8-proxy/glasswall-desktop#60]
I get a page not found error on try to download the glasswall desktop app. Here is the link that is being tried to access.
https://github.com/k8-proxy/glasswall-desktop/releases/download/v0.1.0/glasswall-desktop-0.1.0.snap

OS - CentOS 7

**Comment by kumarsudhish** [comment]
Verified this issue as post release and under got action could see Ubuntu build getting pushed.
Hence marking this issue as Closed.


![image](https://user-images.githubusercontent.com/71662255/97702795-97ad3800-1ad5-11eb-9d13-cd1597ee30ae.png)
