### ISSUE TITLE
Live Portal: Happy User/Stargazers/Forks count on glasswall-desktop web portal is wrong and on clicking it point to wrong repo

### ISSUE THREAD

**Issue by kumarsudhish** [k8-proxy/glasswall-desktop#74]
Live Portal: Happy User/Stargazers/Forks count on glasswall-desktop web portal is wrong and on clicking it point to wrong repo

![image.png](https://images.zenhubusercontent.com/5f6b4534c344a37b7c855e35/82fe128b-6b05-4f03-aca0-a135ebc17921)

**Comment by dinis-cruz-gw** [comment]
I removed this panel , so this bug is not there anymore
