### ISSUE TITLE
Create file analysis report with local docker

### ISSUE THREAD

**Issue by gmuditdce** [k8-proxy/glasswall-desktop#96]
Create file analysis report with local docker

**Comment by kumarsudhish** [comment]
Verified this issue on latest build from Repo and observed that issue has been fixed.
Analysis is done locally and no API call is made to the cloud.
Attaching screenshot or same.

![DockerAnalysis](https://user-images.githubusercontent.com/71662255/97407542-d51c9480-1920-11eb-803b-1a21a1e8f883.JPG)
![DockerAnalysis_1](https://user-images.githubusercontent.com/71662255/97407546-d6e65800-1920-11eb-9f8e-5814084520cf.JPG)
![DockerAnalysis_2](https://user-images.githubusercontent.com/71662255/97407549-d77eee80-1920-11eb-9199-d578f00d7c97.JPG)

Hence marking this issue as Done.
